# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 71184d7acd800ecab6fa4e16b2b537d903700cc5ae7b01146c33ec0e17e464eb26ed9c93a9aaea6fa3b6b44fef4d4ed08e0c20387b9e87a677d5054d24227c86

test:
  secret_key_base: 8346346f61f6e4706f0c1b5ce527972397653132e6731588a37d322199ce0652ced44f59b62f7069375a30015228342085faa6e2d77d9e7f0f84ac457a9244a7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
